require("sosring.plugins-setup")
require("sosring.core.options")
require("sosring.core.keymaps")
require("sosring.core.colorscheme")
require("sosring.plugins.lualine")
require("sosring.plugins.autopairs")
